_format_version: "3.0"
_transform: true

services:
  - name: api-service-java
    url: http://host.docker.internal:8080
    routes:
      - name: rota-appointments
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        paths:
          - /api/v1/appointments
        strip_path: false
    plugins:
      - name: auth-rbac
  - name: graphql-service-java
    url: http://host.docker.internal:8084
    routes:
      - name: rota-graphql
        methods:
          - GET
          - POST
          - OPTIONS
        paths:
          - /graphql
        strip_path: false
    plugins:
      - name: auth-rbac
